In [1]:
import numpy as np

### 1. Creating NumPy Arrays

In [2]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

#### Creting range of array with start and stop parameter

In [3]:
np.arange(10,23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [4]:
len(np.arange(10,23))

13

In [5]:
my_range_array = np.arange(10,23)

In [6]:
my_range_array.size

13

#### linspace(), zeros(), ones(), and NumPy data types 

###### linspace()

In [7]:
np.linspace(5,15,9)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [8]:
my_linspace = np.linspace(5,15,9, retstep=True)

In [9]:
my_linspace

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

##### zeros()

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

##### data types

In [11]:
np.zeros(11, dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)


### 2. Index, Slice, Itterate

#### Slice arrays

In [12]:
my_vector = np.array([-17, -4, 5, 7, 0, 2, 21, 37, 105])

In [13]:
my_vector.sort()

In [14]:
my_vector

array([-17,  -4,   0,   2,   5,   7,  21,  37, 105])

In [15]:
my_vector[0] = -102

In [16]:
my_vector[-3]

21

##### Two dimensional arrays

In [17]:
my_array_2 = np.arange(35)
my_array_2.shape = (7,5)
my_array_2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

#### Boolean Mask Arrays

In [18]:
zero_mod_7_mask = 0 == (my_vector % 7)
zero_mod_7_mask

array([False, False,  True, False, False,  True,  True, False,  True])

In [19]:
sub_array = my_vector[zero_mod_7_mask]

In [20]:
sub_array

array([  0,   7,  21, 105])

In [21]:
sub_array[sub_array > 0]

array([  7,  21, 105])

##### NumPy logical operation

In [22]:
mod_test = 0 == (my_vector % 7)

In [23]:
possitive_test = my_vector > 0

In [24]:
comined_mask = np.logical_and(mod_test, possitive_test)

In [25]:
comined_mask

array([False, False, False, False, False,  True,  True, False,  True])

In [26]:
my_vector[comined_mask]

array([  7,  21, 105])

#### Broadcasting  

In [28]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [29]:
# shape 
my_3D_array.shape

(2, 7, 5)

In [30]:
# number of dimmesions 
my_3D_array.ndim

3

In [31]:
# size; number of elements 
my_3D_array.size

70

In [32]:
# data type for each element
my_3D_array.dtype

dtype('int32')

In [33]:
5 * my_3D_array -2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [40]:
# broadcasting
left_mat = np.arange(6).reshape((2,3))
right_mat = np.arange(15).reshape((3,5))

In [41]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [42]:
my_3D_array.sum()

2415

### Structured Arrays

In [48]:
person_data_def = [('name', 'S6'),('height', 'f8'),('weight', 'f8'), ('age', 'i8')];

In [49]:
person_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [50]:
people_array = np.zeros((4), dtype=person_data_def)

In [53]:
people_array[3] = ('Delta', 73, 205, 34)

In [54]:
people_array

array([(b'',  0.,   0.,  0), (b'',  0.,   0.,  0), (b'',  0.,   0.,  0),
       (b'Delta', 73., 205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [55]:
# obtaining information from first element through last element
people_array[0:]

array([(b'',  0.,   0.,  0), (b'',  0.,   0.,  0), (b'',  0.,   0.,  0),
       (b'Delta', 73., 205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [56]:
ages = people_array['age']

In [57]:
ages

array([ 0,  0,  0, 34], dtype=int64)

##### Multi-dimensional Structured Arrays

In [58]:
people_big_array = np.zeros((4,3,2), dtype=person_data_def)

In [59]:
people_big_array

array([[[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])